### ISSUE TITLE
Session Id not getting created

### ISSUE THREAD

**Issue by rajamurugan44** [krishnavelu/alice_blue#439] opened 2022-09-10 11:33 UTC
Get Encryption Key response {"userId":null,"userData":null,"encKey":"Z453LT8VDGDB","apikey":null,"stat":null,"emsg":null,"loginType":null,"version":null,"login":false}

Getting User ID and null and session id not got created..

 Object of type bytes is not JSON serializable

**Comment by krishnavelu** [comment] 2022-09-10 12:35
Post what you are trying and what error you are getting.
Without this I cannot help.

Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue...

**Comment by rajamurugan44** [comment] 2022-09-11 05:31
data = {"userId" : username,
                "userData" : checksum.}

checkSum is coming with b'**************' so its not getting response.. Used checksum.decode('utf-8') to remove b' from checksum token.. Now in  r = requests.post(AliceBlue.__urls["twoFA"], json=data) there is no response..

**Comment by krishnavelu** [comment] 2022-09-11 12:21
What are you trying to do?

**Comment by rajamurugan44** [comment] 2022-09-11 12:33
Trying to login and session id is not getting created.. Pls check it.. Sending valid user id, password, two_FA, api_key and secret.. But its not getting created

**Comment by krishnavelu** [comment] 2022-09-11 13:32
Enable logging and post the logging results

**Comment by krishnavelu** [comment] 2022-09-11 14:46
Duplicate of #440.
Follow this.

**Closed as completed by krishnavelu** 2022-09-11 14:46 UTC
