### ISSUE TITLE
Getting different scrip than what is subscribed

### ISSUE THREAD

**Issue by Kannansowmyan** [krishnavelu/alice_blue#41] opened 2019-12-17 08:38 UTC
Hi, firstly thanks for the code, i am able to connect and start testing.  When i search for the scrip i am getting the correct results... however when i subscribe for live feed using the same values, i get different script. Please find the code snippet and output screenshot.

print("------\n")
print(alice.get_instrument_by_symbol('NSE','RELIANCE'))
print("\n------\n")
socket_opened = False
def event_handler_quote_update(message):
    print(f"quote update {message}")

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
while(socket_opened==False):
    pass
alice.subscribe(alice.get_instrument_by_symbol('NSE', 'RELIANCE'), LiveFeedType.COMPACT)
time.sleep(10)

Result screenshot
![image](https://user-images.githubusercontent.com/28265903/70978931-b0d41280-20d6-11ea-8af6-3b48eeac12bd.png)

**Comment by Kannansowmyan** [comment] 2019-12-17 09:30
Just an update to the issue.  I tried to get what is the data being returned in the list of contract.  You find same token number across exchange. i.e. 2885 is in both NSE and CDS.  Hence the instrument masterlist is returning whichever is matching .

**Comment by Kannansowmyan** [comment] 2019-12-17 12:38
Update 2: Managed to make it work by making changes to the source code. Not sure whether this is the correct way. enclosing the file (Added one more parameter for get_instrument_by_token exchange to filter exchange wise
[alice_blue_py.txt](https://github.com/krishnavelu/alice_blue/files/3973288/alice_blue_py.txt)

**Comment by krishnavelu** [comment] 2019-12-17 13:03
Strange, will look into the issue.

**Comment by krishnavelu** [comment] 2019-12-26 14:39
Hi @Kannansowmyan 
Thanks for reporting this strange issue.

This seems to be a problem in alice server and not in library. Here is my explanation.
1. In the second line of your code 
`print(alice.get_instrument_by_symbol('NSE','RELIANCE'))` You are printing the instrument. And this shows correct instrument (Reliance from NSE, not CDS). This proves that library fetches correct instrument-reliance.
2. In the quote update also the `exchange` key shows as `NSE` not `CDS`. 
3. In quote update, 1559.45 is `ltp` price is of reliance's, it cannot be the price of usdinr call option. 
4. Only in `instrument` key is shown as usdinr's instrument.

![image](https://user-images.githubusercontent.com/38440742/71479437-6895ae00-27c2-11ea-842d-f8b775062693.png)

As CDS is not enabled in my account. I'm not able to reproduce this issue in my end. Will followup with alice & tradelab regarding this issue.

**Comment by krishnavelu** [comment] 2019-12-27 14:54
I’m looking into this issue, for now you can avoid this by not downloading the CDS master contract.

**Comment by krishnavelu** [comment] 2019-12-28 15:15
@Kannansowmyan I've fixed in develop branch. I couldn't test your particular issue because CDS is not enabled in my account. Please test and let me know if this solves your problem.

**Comment by krishnavelu** [comment] 2020-03-01 18:21
@Kannansowmyan did you test it?
I cannot test it because CDS is not enabled in my account.

**Comment by Kannansowmyan** [comment] 2020-03-02 13:26
Give me few days sir. Testing it. Should confirm.
Regards
Kannan

**Comment by krishnavelu** [comment] 2020-03-15 17:07
I'm waiting for your test results on 0.0.7 release. If this goes good. I'll make a new release which has many bug fixes & enhancements.

**Comment by krishnavelu** [comment] 2020-03-23 02:57
Hello @Kannansowmyan 
Any updates?

**Comment by krishnavelu** [comment] 2020-04-12 15:02
@Kannansowmyan any updates?
Closing this now.

**Comment by Chawdavijay** [comment] 2020-04-19 21:12
This is still arising... 
I am calling "get_instrument_by_symbol" function through API for Reliance then i am getting Token as 2885 for Reliance.
But when i am calling "get_instrument_by_token" function through API for 2885 then i am getting instrument as USDINR.

**Comment by krishnavelu** [comment] 2020-05-09 22:37
@Chawdavijay 
Which version of the library are you using?
Post some sample code to reproduce the issue. Also the results/prints.

**Comment by krishnavelu** [comment] 2020-05-20 02:16
@Chawdavijay your problem solved?

**Comment by Chawdavijay** [comment] 2020-05-20 09:40
> @Chawdavijay your problem solved?

I am using your library with latest version only. 
Now I am subscribe the instruments by name.

**Comment by krishnavelu** [comment] 2020-05-23 16:45
I'm getting reliance as instrument and reliance's quote when subscribe.

```
------

Instrument(exchange='NSE', token=2885, symbol='RELIANCE', name='RELIANCE INDUSTRIES LTD', expiry=None, lot_size=None)

------

quote update {'exchange': 'NSE', 'token': 2885, 'ltp': 1431.55, 'change': 0, 'exchange_time_stamp': 0, 'volume': 17458503}
```

**Closed as completed by krishnavelu** 2020-05-23 16:45 UTC
Labels: bug
