### ISSUE TITLE
TypeError: Object of type bytes is not JSON serializable

### ISSUE THREAD

**Issue by RRR008** [krishnavelu/alice_blue#454] opened 2022-09-19 14:57 UTC
Hi @krishnavelu ,
I am trying to get session Id by taking reference of the code mentioned in the SDK but I am getting error as : 

Exception in thread Thread-2 (RunAlgoClick):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Ritesh/Documents/Algo/InfiniteAlgo_V_2.0.5.py", line 1550, in RunAlgoClick
    RunAlgoClick1(username,api_secret,targe_profit,final_target,stop_loss,expYear,expMonth,expDay,PandM,twoFA,password,appid)
  File "/Users/Ritesh/Documents/Algo/InfiniteAlgo_V_2.0.5.py", line 382, in RunAlgoClick1
    session_id = AliceBlue.login_and_get_sessioID(  username    = usernameVal, 
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/alice_blue/alice_blue.py", line 204, in login_and_get_sessioID
    r = requests.post(AliceBlue.__urls["webLogin"], json=data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

Below is the code I am using to get the sessi
<img width="1253" alt="Screenshot 2022-09-19 at 8 22 22 PM" src="https://user-images.githubusercontent.com/108396628/191047612-96fcb1f8-dca6-45aa-ac12-58434ea4f5e5.png">
on_id:

I have used your previous sdk and same was working according to the steps mentioned in the site but for the V2 it's not the same please let me know what exactly is happing why same code mentioned in the SDK is not working for me.

Please help me on this 

Thank you

**Comment by krishnavelu** [comment] 2022-09-20 01:01
Duplicate of #440

**Closed as completed** 2022-09-21 00:54 UTC
