### ISSUE TITLE
Intermittent issue

### ISSUE THREAD

**Issue by dhayal123** [krishnavelu/alice_blue#139] opened 2020-06-21 13:04 UTC
Hi Krishna,

I am getting the below error message intermittently. Few times, it works and fetches the data. Not sure, why am I getting this intermittent issue? can you suggest a fix? Thanks in advance

    alice = AliceBlue(username='username', password='password', access_token=access_token, master_contracts_to_download=['NFO','NSE','MCX'])      
  File "c:\Python_Webapp\backend py\alice_blue.py", line 210, in __init__
    raise Exception(f"Couldn't get profile info with credentials provided '{e}'")
Exception: Couldn't get profile info with credentials provided '{"status":"error","message":"Request Unauthorised","data":{}}'

**Comment by krishnavelu** [comment] 2020-06-21 13:06
You'll get this if your `access_token` is invalid.

**Comment by dhayal123** [comment] 2020-06-21 13:10
is there a fix for it? because access_token is generated by system. I dont think, we can do anything on this.

**Comment by krishnavelu** [comment] 2020-06-21 13:12
what fix you are expecting? `access_token` should be generated once a day. Stored in a file & reuse for 24Hrs. Once you login though app, your `access_token` gets invalid. So when you are using API, don't access through app.

**Comment by dhayal123** [comment] 2020-06-21 13:20
Thanks. closing the ticket

**Comment by jaydave1988** [comment] 2020-06-21 18:49
@krishnavelu I am facing the same issue. After creating new access_token also giving "status":"error","message":"Request Unauthorised","data":{}...
This is intermittent issue and I dont think so there is any relation between login through app.

**Comment by krishnavelu** [comment] 2020-06-23 03:30
I’ll look in to it. But I don’t have any hope it can be resolved.

**Comment by jaydave1988** [comment] 2020-06-23 03:43
I know, it is very hard to debug as it is randomly generating and we cant tell that only particular api is generating issue. Sometimes issue is coming while placing order, sometimes it is coming in get_profile and sometimes in get_position_book.
I am trying to debug this from 3-4 days, but I am not able to find anything.

But I noticed one thing, After generating new access_token, I am not able to alice_blue object as it is failing in get_profile method. 
Do you think it is because of cache or cookie generation? 

Only one thing we can do is having fallback mechanism in all APIs, i.e. if this type of error is coming than retry after few seconds.

**Comment by kamaleshvm** [comment] 2020-06-24 06:13
I'm also facing the same issue , the error appear randomly for 2 or 3 min and gone.

11:36:32.820000 :buy SL placed  order book price 1C AXISBANK 437.0
11:36:35.385000 :buy Target order place order book 1A AXISBANK 429.0
11:37:02.884000 PROFIT SL error 40Z BPCL {"status":"error","message":"Request Unauthorised","data":{}}
11:38:22.370000 PROFIT SL error 40Z UPL {"status":"error","message":"Request Unauthorised","data":{}}
11:40:06.074000 PROFIT SL error 40Z AXISBANK {"status":"error","message":"Request Unauthorised","data":{}}
11:43:16.069000 PROFIT SL error 40Z AXISBANK {"status":"error","message":"Request Unauthorised","data":{}}

**Comment by kamaleshvm** [comment] 2020-06-24 06:16
I generate the access token multiple time , still this error comes. Got the access token just now.
11:46:05.606000 PROFIT SL error 40Z BPCL {"status":"error","message":"Request Unauthorised","data":{}}

{"status":"error","message":"Request Unauthorised","data":{}}
11:51:53.580000 :SLM loop error 15 {"status":"error","message":"Request Unauthorised","data":{}}

**Comment by jaydave1988** [comment] 2020-06-24 06:33
This issue is coming from last one week. Today also I faced the same issue.
I think problem is coming from alice blue server and it is throwing the error. I noticed one thing that you cant login through ant.aliceblue at the same time when error is coming as server might be down.
But after few minutes(2-3 minutes), calls are executed successfully and we can login also through portal.

**Comment by kamaleshvm** [comment] 2020-06-24 06:39
The issue at aliceblue side, every one hour or sometime it is not responding for basic request

Received access_token: gjjZ4Up_20_aeF4BS7NJwMI4i8A4kFeMsrVuRtlhOqs.nY4QOwnNy1s4nHSxfeLopBbv15B0aft6P2Fw3JDQqu0
null
{'Content-Type': 'application/json', 'client_id': 'XX', 'authorization': u'Bearer gjjZ4Up_20_aeF4BS7NJwMI4i8A4kFeMsrVuRtlhOqs.nY4QOwnNy1s4nHSxfeLopBbv15B0aft6P2Fw3JDQqu0'}
https://ant.aliceblueonline.com/api/v2/contracts.json?exchanges=NSE
Instrument(exchange=u'NSE', token=3499, symbol=u'TATASTEEL', name=u'TATA STEEL LIMITED', expiry=None, lot_size=None)
null
{'Content-Type': 'application/json', 'client_id': 'XX', 'authorization': u'Bearer gjjZ4Up_20_aeF4BS7NJwMI4i8A4kFeMsrVuRtlhOqs.nY4QOwnNy1s4nHSxfeLopBbv15B0aft6P2Fw3JDQqu0'}
https://ant.aliceblueonline.com/api/v2/cashposition
Traceback (most recent call last):

**Comment by jaydave1988** [comment] 2020-06-24 07:11
As I suggested earlier, only one thing we can do in library is having fallback mechanism in all APIs, i.e. if this type of error is coming than retry after few seconds.

**Comment by PranavSonar** [comment] 2020-06-24 09:44
> As I suggested earlier, only one thing we can do in library is having fallback mechanism in all APIs, i.e. if this type of error is coming than retry after few seconds.

Yesterday same kind of issue happened aliceblue change margin requirement around 10AM. All my orders got rejected with error "Margin not available". I was not able to exit also. It last around 7-8 min.I came to know its usual activity from broker to change margin requirement, usually it takes 1-2 min. How you guys are handling this? I had to exit manually.
Also, if we wait few seconds or min we may miss many ticks.

**Comment by jaydave1988** [comment] 2020-06-24 10:58
We cant do anything if we receive margin not available error.
Yes if we wait for few seconds/mins, we will surely miss many ticks..

**Comment by kamaleshvm** [comment] 2020-06-24 13:33
the url error posted below,  some cloudflare security dropping the connection.  Alice blue should remove for api access




 <html class="no-js" lang="en-US"> 
<head>
<meta http-equiv="refresh" content="0">

<title>ant.aliceblueonline.com | 502: Bad gateway</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>




</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="cf-error-details-wrapper">
        <div class="cf-wrapper cf-error-overview">
            <h1>
              
              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">502</span>
              <small class="heading-ray-id">Ray ID: 5a84de52ead1ee7d &bull; 2020-06-24 07:52:17 UTC</small>
            </h1>
            <h2 class="cf-subheadline">Bad gateway</h2>
        </div>
        
        <div class="cf-section cf-highlight cf-status-display">
            <div class="cf-wrapper">
                <div class="cf-columns cols-3">
                  
<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-browser"></i>
    <i class="cf-icon-status cf-icon-ok"></i>
  </div>
  <span class="cf-status-desc">You</span>
  <h3 class="cf-status-name">Browser</h3>
  <span class="cf-status-label">Working</span>
</div>

<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-cloud"></i>
    <i class="cf-icon-status cf-icon-ok"></i>
  </div>
  <span class="cf-status-desc">Paris</span>
  <h3 class="cf-status-name">Cloudflare</h3>
  <span class="cf-status-label">Working</span>
</div>

<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-server"></i>
    <i class="cf-icon-status cf-icon-error"></i>
  </div>
  <span class="cf-status-desc">ant.aliceblueonline.com</span>
  <h3 class="cf-status-name">Host</h3>
  <span class="cf-status-label">Error</span>
</div>

                </div>
              
            </div>
        </div>

        <div class="cf-section cf-wrapper">
            <div class="cf-columns two">
                <div class="cf-column">
                    <h2>What happened?</h2>
                    <p>The web server reported a bad gateway error.</p>
                </div>
              
                <div class="cf-column">
                    <h2>What can I do?</h2>
                    <p>Please try again in a few minutes.</p>
                </div>
            </div>
              
        </div>

        <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>5a84de52ead1ee7d</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Your IP</span>: 5.135.170.250</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div>


    </div>
</div>
</body>
</html>

**Comment by krishnavelu** [comment] 2020-06-28 17:06
I generate `access_token` only once a day, create object only once a day. I don't face this problem often. But If I try to generate `access_token` multiple times a day, I'll also land in to this problem once in a while. This is too hard to reproduce.

If anyone can work with me to reproduce this issue consistently, I can solve this. Until then we need to live with this and follow the way I'm using this. One `access_token` one object per day.

To all who are facing this problem, try to find steps to reproduce this consistently.

**Comment by krishnavelu** [comment] 2021-01-19 01:56
Closing this as of now. Reopen if needed.

**Closed as completed by krishnavelu** 2021-01-19 01:56 UTC

**Comment by peeper35** [comment] 2021-02-08 05:48
This Bad Gateway 502 thing has been happened to me today, while `TranscationType.Sel`l it executed the order properly but after some amount of time while `TranscationType.Buy` the api gave me the Bad Gateway error. I have not created more than one instance of my alice blue account api. Such errors can cause a big losses to the algos that has been running independently on VPS and when no one is monitoring the execution of the algo. While this happened with me today, I was monitoring the algo and i squared off manually, it saved me from losses. Alice Blue should do something for this. 

![WhatsApp Image 2021-02-08 at 11 16 05](https://user-images.githubusercontent.com/24529163/107180720-4b8c6080-69ff-11eb-9478-a13a032b2b2e.jpeg)

PFA

**Comment by krishnavelu** [comment] 2021-02-09 04:22
Yup. `Alice Blue should do something for this.`
Contact Alice customer care.

**Comment by vetri-trading** [comment] 2021-11-17 11:44
> the url error posted below, some cloudflare security dropping the connection. Alice blue should remove for api access
> 
> <title>ant.aliceblueonline.com | 502: Bad gateway</title> <style type="text/css">body{margin:0;padding:0}</style>
> ```
> <div id="cf-error-details" class="cf-error-details-wrapper">
>     <div class="cf-wrapper cf-error-overview">
>         <h1>
>           
>           <span class="cf-error-type">Error</span>
>           <span class="cf-error-code">502</span>
>           <small class="heading-ray-id">Ray ID: 5a84de52ead1ee7d &bull; 2020-06-24 07:52:17 UTC</small>
>         </h1>
>         <h2 class="cf-subheadline">Bad gateway</h2>
>     </div>
>     
>     <div class="cf-section cf-highlight cf-status-display">
>         <div class="cf-wrapper">
>             <div class="cf-columns cols-3">
> ```
> 
> You
> ### Browser
> Working
> Paris
> ### Cloudflare
> Working
> ant.aliceblueonline.com
> ### Host
> Error
> ```
>             </div>
>           
>         </div>
>     </div>
> 
>     <div class="cf-section cf-wrapper">
>         <div class="cf-columns two">
>             <div class="cf-column">
>                 <h2>What happened?</h2>
>                 <p>The web server reported a bad gateway error.</p>
>             </div>
>           
>             <div class="cf-column">
>                 <h2>What can I do?</h2>
>                 <p>Please try again in a few minutes.</p>
>             </div>
>         </div>
>           
>     </div>
> 
>     <div class="cf-error-footer cf-wrapper">
> ```
> 
> Cloudflare Ray ID: **5a84de52ead1ee7d** • Your IP: 5.135.170.250 • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer)
> 
> ```
> </div>
> ```

Hi,

Have you found any solution for this?
I have faced the same error today.
