### ISSUE TITLE
Bracket order bug for buy in cash segment

### ISSUE THREAD

**Issue by bhushanjawle** [krishnavelu/alice_blue#186] opened 2020-08-28 04:26 UTC
I have been using BO successfully for some time with Limit (sell), however recently in implementation of breakout strategy have found that orders are triggered and closed immediately with 5 paisa difference.

Initially I thought it might be prices running away but that is not the case. 
Both SL and Target are far away but still no change.

Especially with buy orders.

Have tried, Limit, SL-L(same trigger and limit price ) and SL-M but same problem.

Has anybody tried and faced similar issue ? I have asked AB support but they seemed to have no answer.

Has it got to do with understanding of usage of API, support of BO in AliceBlue or API implementation, I am not sure hence posting here for better understanding.
Thanks

**Comment by jaydave1988** [comment] 2020-08-28 04:31
I am hitting the same issue from last 2 days.. It was working fine till then.. Today also I faced in NMDC buy order..

**Comment by bhushanjawle** [comment] 2020-08-28 05:39
> I am hitting the same issue from last 2 days.. It was working fine till then.. Today also I faced in NMDC buy order..

Same here. Same security as well 2 days ago !

**Comment by krishnavelu** [comment] 2020-08-30 14:59
Try some other scrip. To see if same behavior.

**Comment by bhushanjawle** [comment] 2020-08-31 13:39
Apart from NMDC, I have seen this in multiple scrips, PVR, ZEEL, RBSBANK, TVSMOTOR are some other examples.

**Comment by bhushanjawle** [comment] 2020-09-02 05:16
I have stopped my two strategies after 2/3 rd of my orders being rejected in this manner for last few days. Any suggestions / ideas how to remedy this ?

**Comment by bhushanjawle** [comment] 2020-09-08 04:16
Gave it a try again, this time monitoring to see if there are any price issues while sending which causes this behavior, nothing of that sort. Looks like a bug as manual execution has no issue. @krishnavelu can you please confirm  if there is a workaround ?

**Comment by krishnavelu** [comment] 2020-09-13 01:54
@jaydave1988 you are also facing the same issue or yours is solved?
@bhushanjawle are you seeing this behavior only through API? Can you try and let me know if you are having the same behavior through app or web?

**Comment by jaydave1988** [comment] 2020-09-13 10:57
@krishnavelu Yes I faced the same issue with few scripts last week. But I am not sure whether it is bug in your library or from alcieblue side..

**Comment by bhushanjawle** [comment] 2020-09-14 06:18
@krishnavelu will try for each of the order types manually as well and update. 
@jaydave1988 are you using any alternative way to execute similar functionality as BO ?

**Comment by bhushanjawle** [comment] 2020-09-17 05:50
@krishnavelu I have been sending manually, finally triggered today and worked fine. Looks like it only fails with API (tried same with API first(SL Limit for Buy above market price), was rejected. This seems like an API only bug with bracket order.
Tried SLM once again for buy, that is rejected as well for (Error message : "Trigger price not found", have tried all 4 combinations of price and trigger price but same error). 
Please have look.

**Comment by jaydave1988** [comment] 2020-09-17 06:03
@bhushanjawle I am trying to switch in MIS order as BO are blocked for some of the scripts and "the great aliceblue" is charging 4 rs for each leg of the BO order.. on and avg. 1500 rs I am paying extra for BO orders.

**Comment by krishnavelu** [comment] 2020-09-20 14:30
Read [this](https://github.com/krishnavelu/alice_blue/tree/develop#read-this-before-creating-an-issue) and follow before creating an issue.
Provide me a reproducible code.

**Comment by bhushanjawle** [comment] 2020-09-21 13:50
@krishnavelu  please read [this](https://github.com/krishnavelu/alice_blue/issues/186#issue-687702193) original description which says, **code used to work**, I have been using it for sell orders, still works, not working for buy orders
It is exact same code in your example code with different instrument and price(which is time sensitive hence irrelevant for reproducing error) hence did not add code here. Instrument and price is the only thing different. There is no similar issue open .

**Comment by krishnavelu** [comment] 2020-09-26 13:02
This is the sample code

```
o = alice.place_order(transaction_type = TransactionType.Buy,
                     instrument = alice.get_instrument_by_symbol('NSE', 'INFY'),
                     quantity = 1,
                     order_type = OrderType.Limit,
                     product_type = ProductType.BracketOrder,
                     price = 910.0,
                     trigger_price = None,
                     stop_loss = 900.0,
                     square_off = 920.0,
                     trailing_sl = None,
                     is_amo = False)
print(o)
```

This is the print output I got.
```
{'status': 'success', 'message': '', 'data': {'oms_order_id': '200926000001994'}}
```

This is how the order looks like in web.

![image](https://user-images.githubusercontent.com/38440742/94341345-94a2c180-ffd6-11ea-8585-8681f12eb6f7.png)

@bhushanjawle I don't see any problem in placing the order.
If you want to explain your problem, explain it with sample code with print output, screen shot. And specifically what priced you used. The problem you stated is square off. It can happen with wrong prices also.

I cannot understand your problem with a simple English description, with no logs, screenshots.

**Comment by bhushanjawle** [comment] 2020-09-29 06:44
@krishnavelu the issue I am reporting is not placing but it places order and immediately closes it. Please find a real order placed as SL Limit order (as I am expecting it to trigger buy at higher price than one in market). It places it and closes it immediately . Manually entering the order worked fine. If I try SLM type BO, it show trigger price 0 even if a non zero value is provided. Attaching both screenshots.
![SLM BO](https://user-images.githubusercontent.com/1283725/94521884-60d0d180-024c-11eb-83f2-0b91c69c2239.jpeg)
![SLL BO](https://user-images.githubusercontent.com/1283725/94521889-629a9500-024c-11eb-8c94-3dd48118602b.jpeg)
Here are relevant code snippets (exactly same as yours other than order type )
```
.......
       transaction_type = TransactionType.Buy if side == 'B' else TransactionType.Sell
       order_type = OrderType.Limit if side == 'S' else OrderType.StopLossLimit 
    #    order_type = OrderType.Limit if side == 'S' else OrderType.StopLossMarket  # This was used for sending SLM BO
    # initialize price target etc
    order_id = broker.place_order(transaction_type = transaction_type,
               instrument = broker.get_instrument_by_symbol('NSE', symbol),
               quantity = quantity,
               order_type = order_type,
               product_type = product_type, #ProductType.BracketOrder,
               price = px,
               trigger_price = trigger_price,
               stop_loss = sl_points,
               square_off = target_points,
               trailing_sl = None,
               is_amo = False)
``` 

Please note earlier I tried to use Limit orders for buy as well, but as this is breakout strategy, they won't work well as they execute immediately if price is favourable compared to limit order.
Trust that gives you all relevant data points.

**Comment by krishnavelu** [comment] 2020-10-03 14:28
![image](https://user-images.githubusercontent.com/38440742/94993982-ac43f200-0562-11eb-8a59-8c8362d7a6b9.png)
If the average price was 132.7 I hope the scrip was at 132.7 at that time.
If the scrip was 132.7 and the trigger price was less than that (132.6) then why would it not trigger?
I still didn't get the point.
What I'm looking for is evidences (print outputs) of what was the scrip price, trigger price, what price it actually executes and what price it closes.

**Comment by krishnavelu** [comment] 2020-10-03 14:34
by the way which version of library you are using?
Try the latest one. Try develop version also 1.0.1

**Comment by bhushanjawle** [comment] 2020-10-04 09:36
Version: 1.0.0. 
Is there a different implementation of in develop you want me to try out ? 
Will need to position size accordingly hence need a confirmation before putting real money. Thanks

**Comment by krishnavelu** [comment] 2020-10-05 02:08
It has some fix related to BO. So try it.

**Comment by krishnavelu** [comment] 2020-10-18 15:11
@bhushanjawle is your issue solved?

**Comment by bhushanjawle** [comment] 2020-10-19 12:27
@krishnavelu , have tried few times but orders were not triggered so can't confirm. Will update

**Comment by krishnavelu** [comment] 2021-01-19 01:47
@bhushanjawle Hope your issue is solved. Closing this as of now. Reopen if needed.

**Closed as completed by krishnavelu** 2021-01-19 01:47 UTC
