### ISSUE TITLE
Some place_order() samples mentioned in description doesnt work.

### ISSUE THREAD

**Issue by amit-kumar27742** [krishnavelu/alice_blue#19] opened 2019-11-08 06:26 UTC
Some place_order() samples mentioned in description doesnt work.

e.g.

```
print ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%4%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
print(
   alice.place_order(transaction_type = TransactionType.Buy,
                     instrument = alice.get_instrument_by_symbol('NSE', 'INFY'),
                     quantity = 1,
                     order_type = OrderType.Limit,
                     product_type = ProductType.BracketOrder,
                     price = 8.0,
                     trigger_price = None,
                     stop_loss = 6.0,
                     square_off = 10.0,
                     trailing_sl = None,
                     is_amo = False)
)
```

Gives error:

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%4%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{'status': 'error', 'message': ' is not supported in NSE segment.', 'data': {}}
```

Parameters looks to be fine. My account also has sufficient balance.

Additional Information:
Looks like sample orders with ProductType.BracketOrder are giving error.

The error message from alice seems vague, so you are the best judge to answer if it is a bug or not. You may replicate yourself.
Thanks.

**Comment by krishnavelu** [comment] 2019-11-09 16:35
I also noticed this while creating the library. I need to contact alice developers or trade lab for this problem. will follow up.

**Comment by viveksoundrapandi** [comment] 2019-11-15 04:28
@krishnavelu any update on this issue. fixing this would be awesome

**Comment by krishnavelu** [comment] 2019-11-15 12:38
Got the root cause of the problem, will be fixing this in develop in this weekend.

**Comment by viveksoundrapandi** [comment] 2019-11-18 06:45
Great thanks 😃

**Comment by krishnavelu** [comment] 2019-11-19 00:32
@viveksoundrapandi, @amit-kumar27742 Fixed this issue in develop. Take develop & test it.
If it works will close this issue.

**Comment by viveksoundrapandi** [comment] 2019-11-19 01:35
@krishnavelu just tested it order is getting placed to alice now , I could validate by getting the order history. Will try out in market hours and verify if it goes through the exchange

**Comment by krishnavelu** [comment] 2019-11-19 01:38
You should get order id. If you get order id, it will work in market hours too...

**Comment by viveksoundrapandi** [comment] 2019-11-19 01:40
@krishnavelu yes it should work but it will fail other cases, as prod_type is defined only inside BO if condition. Just tried place a CO order and it fails as expected:
```
 File "/app/alice_blue/alice_blue/alice_blue.py", line 490, in place_order
    'product':prod_type,
UnboundLocalError: local variable 'prod_type' referenced before assignment

```

**Comment by krishnavelu** [comment] 2019-11-19 04:02
Nice catch, yea missed it. Will fix soon.

**Comment by krishnavelu** [comment] 2019-11-20 03:27
@viveksoundrapandi Hope this fixes it.
Please test and let me know.

**Comment by krishnavelu** [comment] 2019-11-23 16:15
@viveksoundrapandi I Hope the issue is solved. 
Closing this issue till I don't get back from you.

**Closed as completed by krishnavelu** 2019-11-23 16:15 UTC
Labels: bug
