### ISSUE TITLE
Alice New API support 

### ISSUE THREAD

**Issue by vinitshetty** [krishnavelu/alice_blue#424] opened 2022-07-04 10:55 UTC
Alice has come up with new set of APIs and authentication mechanism. 

Any roadmap to support this? 

Below are the docs- 
https://v2api.aliceblueonline.com/introduction

**Comment by jaydave1988** [comment] 2022-07-04 11:00
Duplicate of #418

**Closed as completed** 2022-09-09 10:59 UTC
